"""
Django settings for DBCA Authorisations project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
VERSION_FILE = BASE_DIR.parent / "VERSION"


def _read_app_version() -> str:
    """Read the canonical application version from the repository VERSION file."""
    # Keep one source of truth for CI tags, deployment manifests, and UI display.
    if not VERSION_FILE.exists():
        return "v0.0.0"

    version = VERSION_FILE.read_text(encoding="utf-8").strip()
    return version if version else "v0.0.0"


APP_VERSION = _read_app_version()

# Initialise environment variables
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
    SECURE_HSTS_SECONDS=(int, 3600 * 24 * 365),  # 1 year
    SECURE_ONLY=(bool, True),
    # File storage
    LOCAL_MEDIA_STORAGE=(bool, False),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Uses DJANGO_SECRET_KEY to avoid Azure Pipelines script env filtering of SECRET_* prefix.
SECRET_KEY = env("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = [
    "localhost",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
]

# Allowed host for UAT and/or production environments
ALLOWED_HOST = env("ALLOWED_HOST", default=None)
if ALLOWED_HOST:
    ALLOWED_HOSTS.append(ALLOWED_HOST)
    CSRF_TRUSTED_ORIGINS.append(f"https://{ALLOWED_HOST}")

# SSL, CSRF and security settings

# Use sessions for CSRF protection without disclosing CSRF token in cookies
CSRF_USE_SESSIONS = True

# Let the application know it's behind a proxy
# and to use the X-Forwarded-* headers for host and protocol information
USE_X_FORWARDED_HOST = True

# Recognise secure connections coming through the proxy (nginx)
# by checking the X-Forwarded-Proto header
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Set custom the CSRF header name that Django will look on the request headers
# for token validation when authenticating via AJAX etc.
CSRF_HEADER_NAME = env("CSRF_HEADER_NAME", default="HTTP_X_CSRFTOKEN")
CSRF_HEADER_CLIENT = env("CSRF_HEADER_CLIENT", default="X-CsrfToken")

# Set custom CSRF cookie name (probably the session key as well)
CSRF_COOKIE_NAME = env("CSRF_COOKIE_NAME", default="csrftoken")

# Non-secure redirection cache: 1 minute in debug mode, 1 year in production
SECURE_HSTS_SECONDS = 60 if DEBUG else env("SECURE_HSTS_SECONDS")
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

if not DEBUG:
    # Ensure SameSite attribute allows "safe" cross-site requests
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"

    # Secure attribute is also recommended if using HTTPS
    SECURE_ONLY = env("SECURE_ONLY")
    CSRF_COOKIE_SECURE = SECURE_ONLY
    SESSION_COOKIE_SECURE = SECURE_ONLY


# Application definition
INSTALLED_APPS = [
    "admin_tools",
    "admin_tools.theming",
    "admin_tools.menu",
    "admin_tools.dashboard",
    "django_vite",
    "adminsortable2",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_jsonform",
    "users",
    "processes",
    "questionnaires",
    "applications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "dbca_utils.middleware.SSOLoginMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "config.cache_control_middleware.GlobalNeverCacheMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        # "APP_DIRS": True,
        "OPTIONS": {
            "debug": DEBUG,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                "django.template.loaders.filesystem.Loader",
                "django.template.loaders.app_directories.Loader",
                "admin_tools.template_loaders.Loader",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db_url(),
}

# Default user model
AUTH_USER_MODEL = "users.User"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-au"

TIME_ZONE = env("TIME_ZONE", default="Australia/Perth")

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# The URL prefix for static files served from STATIC_ROOT
STATIC_URL = "static/"

# The directory where the collected static files will be served from
STATIC_ROOT = BASE_DIR / "static"

# The source of static files when doing collectstatic
STATICFILES_DIRS = [
    BASE_DIR / "assets",
]

# Storage Backends
STORAGES = {
    # Avoid using the default FileSystemStorage and MEDIA_ROOT for uploaded files,
    # as they are publicly accessible and not suitable for sensitive data.
    "default": {
        "BACKEND": "config.storage.PrivateMediaStorage",
    },
    # Use whitenoise to add compression and caching support for static files.
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Original frontend build directory - doesn't exist in docker environment
FRONTEND_DIST = Path(os.path.abspath(BASE_DIR / "../frontend/dist"))
if FRONTEND_DIST.exists():
    STATICFILES_DIRS.append(FRONTEND_DIST)

# Frontend manifest.json path
# (to avoid a warning while doing "collectstatic" the first time)
MANIFEST_PATH = None
if os.path.exists(FRONTEND_DIST / "manifest.json"):
    MANIFEST_PATH = FRONTEND_DIST / "manifest.json"
elif os.path.exists(BASE_DIR / "assets" / "manifest.json"):
    MANIFEST_PATH = BASE_DIR / "assets" / "manifest.json"

DJANGO_VITE = {
    "default": {
        "manifest_path": MANIFEST_PATH,
        "dev_mode": env("DEBUG_FRONTEND", cast=bool, default=False),
        # If the `DEBUG_FRONTEND` is True, then the plugin will need the below settings
        "dev_server_host": ALLOWED_HOST if ALLOWED_HOST else "localhost",
        "dev_server_protocol": "https" if ALLOWED_HOST else "http",
        # The plugin doesn't support stripping the port.
        # `None` will actually add string "None" and will not work
        "dev_server_port": None if ALLOWED_HOST else 5173,
    }
}

# Admin dashboard configuration
ADMIN_TOOLS_INDEX_DASHBOARD = "config.dashboard.CustomIndexDashboard"
ADMIN_TOOLS_APP_INDEX_DASHBOARD = "config.dashboard.CustomAppIndexDashboard"

# Explicitly set the model backend
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
]

# auth2: only allow accounts with specific email suffixes
ALLOWED_EMAIL_SUFFIXES = []


# Django Rest Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "UPLOADED_FILES_USE_URL": False,
}

# --- Private Media Storage for Secure File Uploads ---

# This setting is explicitly `None` as the Azure File Storage filesystem
# belongs to `root` user, otherwise will throw `PermissionError` on file uploads
FILE_UPLOAD_PERMISSIONS = None

# Assume Azure blob storage is used for media uploads, unless explicitly set as local storage.
LOCAL_MEDIA_STORAGE = env("LOCAL_MEDIA_STORAGE")
if LOCAL_MEDIA_STORAGE:
    # This directory should be local or mounted storage in AKS and not served by any server
    PRIVATE_MEDIA_ROOT = env("PRIVATE_MEDIA_ROOT")
    # Ensure that the private media directory exists.
    if not os.path.exists(PRIVATE_MEDIA_ROOT):
        os.makedirs(PRIVATE_MEDIA_ROOT)
else:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.azure_storage.AzureStorage",
    }
    AZURE_ACCOUNT_NAME = env("AZURE_ACCOUNT_NAME")
    AZURE_CONTAINER = env("AZURE_CONTAINER")
    AZURE_SAS_TOKEN = env("AZURE_SAS_TOKEN")


# Maximum allowed file size for uploads: 10MB
UPLOAD_MAX_SIZE = 10 * 1024 * 1024

# Allowed mime types for uploaded files
UPLOAD_MIME_TYPES = [
    "image/jpeg",
    "image/png",
    "application/pdf",
    # "application/msword", # don't accept old format
    # "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    # "application/vnd.ms-excel", # don't accept old format
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
]


# Cloudflare Turnstile configuration
TURNSTILE_SITE_KEY = env("TURNSTILE_SITE_KEY", default=None)
TURNSTILE_SECRET_KEY = env("TURNSTILE_SECRET_KEY", default=None)
