# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - group: docker-build-variables
  - name: tag
    value: '$(Build.BuildId)'
  - name: tagDate
    value: $[ format('{0:yyyy}.{0:MM}.{0:dd}.{0:HH}.{0:mm}{0:ss}', pipeline.startTime) ]
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  - name: isDev
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/uploads-backend')]

stages:
- stage: Build
  condition: and(succeeded(), eq(variables.isMain, 'true'))
  displayName: Build Docker Image
  jobs:
  - job: BuildThenPush
    displayName: Build then Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Bash@3
      displayName: Write secret to temporary files
      inputs:
        targetType: inline
        script: |
          mkdir -p /tmp/docker-secrets
          echo -n '$(SECRET_KEY)' > /tmp/docker-secrets/SECRET_KEY
          chmod 600 /tmp/docker-secrets/*
    - task: Docker@2
      displayName: Build Docker Image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: DockerGitHub
        repository: dbca-wa/authorisations
        tags: |
          latest
          $(tagDate)
        arguments: |
          --secret id=SECRET_KEY,src=/tmp/docker-secrets/SECRET_KEY
          --build-arg DATABASE_URL=$(DATABASE_URL)
          --build-arg LOCAL_MEDIA_STORAGE=$(LOCAL_MEDIA_STORAGE)
          --build-arg PRIVATE_MEDIA_ROOT=$(PRIVATE_MEDIA_ROOT)
      env:
        DOCKER_BUILDKIT: 1
    - task: Bash@3
      displayName: Clean up secret files
      condition: always()
      inputs:
        targetType: inline
        script: |
          rm -rf /tmp/docker-secrets
    - task: Docker@2
      displayName: Push Docker Image
      inputs:
        command: push
        containerRegistry: DockerGitHub
        repository: dbca-wa/authorisations
        tags: |
          latest
          $(tagDate)
    # - task: Docker@2
    #   displayName: Dev Build image and Push
    #   inputs:
    #     command: buildAndPush
    #     dockerfile: '$(Build.SourcesDirectory)/dockerdev/Dockerfile'
    #     tags: |
    #           authorisations_dev_latest
    #           authorisations_dev_$(tagDate)
    #     containerRegistry: DockerGitHub
    #     repository: ghcr.io/dbca-wa/docker_app_dev
    #   env:
    #     DOCKER_BUILDKIT: 1
