# Generated by Django 5.2 on 2025-07-29 04:04

import django.db.models.deletion
import django_jsonform.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(db_index=False, max_length=20)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('document', django_jsonform.models.fields.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('slug'), models.OrderBy(models.F('version'), descending=True), include=('name',), name='qnaire_unique_slug_version_desc')],
            },
        ),
    ]
