# Generated by Django 5.2 on 2025-08-12 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, editable=False),
        ),
    ]
