# Generated by Django 5.2.7 on 2025-11-04 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnairePermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codename', models.SlugField(help_text="Machine-readable permission identifier, e.g. 'view_applications'.", max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human readable permission name.', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description/help text.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Questionnaire permission',
                'verbose_name_plural': 'Questionnaire permissions',
                'ordering': ('codename',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='questionnaires.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(help_text='Permissions assigned to this user for this questionnaire.', related_name='+', to='questionnaires.questionnairepermission')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('questionnaire', 'user')},
            },
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who participate in managing (or reporting) this questionnaire.', null=True, related_name='+', through='questionnaires.QuestionnaireMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
