# Generated by Django 5.2.9 on 2026-02-10 07:53

import questionnaires.bugfix
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='document',
            field=questionnaires.bugfix.DocumentJSONField(),
        ),
    ]
