# Generated by Django 5.2.9 on 2026-03-05 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
        ('questionnaires', '0002_alter_questionnaire_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questionnaire',
            name='qnaire_unique_slug_version_desc',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='slug',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='process',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questionnaires', to='processes.authorisationprocess'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='questionnaire',
            constraint=models.UniqueConstraint(models.F('process'), models.F('name'), models.OrderBy(models.F('version'), descending=True), name='qnaire_unique_process_name_version_desc'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(help_text='The unique name of the questionnaire within the process such as; "New application", "Renewal" etc.', max_length=100),
        ),
    ]
