# Generated by Django 5.2.9 on 2026-02-18 04:48

import applications.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('key', models.UUIDField(default=uuid.uuid6, editable=False, unique=True)),
                ('question', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=applications.models.attachment_upload_path)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('application', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='applications.application')),
            ],
            options={
                'indexes': [models.Index(fields=['application', 'is_deleted'], name='attachments_app_deleted_idx')],
            },
        ),
    ]
