# Generated by Django 5.2.15 on 2026-07-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DISCARDED', 'Discarded'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_ASSESSMENT', 'Under Assessment'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CONDITIONS', 'Approved With Conditions'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], default='DRAFT', editable=False, max_length=30),
        ),
    ]
