# Generated by Django 5.2.15 on 2026-08-12 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationattachment',
            name='size',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
