# Generated by Django 5.2.9 on 2026-03-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorisationprocess',
            name='reviewer_groups',
            field=models.ManyToManyField(blank=True, help_text='Reviewer groups responsible for this authorisation process.', related_name='+', to='auth.group'),
        ),
    ]
