# Generated by Django 5.2.15 on 2026-07-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('processes', '0002_authorisationprocess_reviewer_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorisationprocess',
            name='assessor_groups',
        ),
        migrations.AddField(
            model_name='authorisationprocess',
            name='reviewer_groups',
            field=models.ManyToManyField(blank=True, help_text='Reviewer groups responsible for this authorisation process.', related_name='+', to='auth.group'),
        ),
    ]
