# Generated by Django 5.2.15 on 2026-08-04 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0004_alter_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISCARDED', 'Discarded'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_ASSESSMENT', 'Under Assessment'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CONDITIONS', 'Approved With Conditions'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], help_text='The application status before the change.', max_length=50)),
                ('next_status', models.CharField(choices=[('DRAFT', 'Draft'), ('DISCARDED', 'Discarded'), ('SUBMITTED', 'Submitted'), ('WITHDRAWN', 'Withdrawn'), ('UNDER_REVIEW', 'Under Review'), ('UNDER_ASSESSMENT', 'Under Assessment'), ('APPROVED', 'Approved'), ('APPROVED_WITH_CONDITIONS', 'Approved With Conditions'), ('DEFERRED', 'Deferred'), ('REJECTED', 'Rejected')], help_text='The application status after the change.', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the status change was recorded (UTC).')),
                ('application', models.ForeignKey(help_text='The application that changed status.', on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='applications.application')),
                ('user', models.ForeignKey(blank=True, help_text='The user who triggered the status change (null if system action).', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application Audit Log',
                'verbose_name_plural': 'Application Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['application', '-timestamp'], name='audit_appli_applica_f95f7b_idx'), models.Index(fields=['user', '-timestamp'], name='audit_appli_user_id_f7ceba_idx'), models.Index(fields=['-timestamp'], name='audit_appli_timesta_077503_idx')],
            },
        ),
    ]
